### ISSUE TITLE
Error on "Check for errors" On Centos 8

### ISSUE THREAD

**Issue by labalex** [PierreGode/Linux-Active-Directory-join-script#11]
Once added to AD, you cannot use "Check for errors" with Centos 8:

![image](https://user-images.githubusercontent.com/7939167/69832526-e9ca4700-11fc-11ea-865d-95797b9e5cbe.png)

**Comment by PierreGode** [comment]
Will be fixed!

**Comment by PierreGode** [comment]
Hi! I have made changes but not able to test them today.

**Comment by PierreGode** [comment]
This has been solved. make sure that you add your domain in netconfig during install in "searchdomain"
and also have in /etc/hosts    host   host.domain.com
