### ISSUE TITLE
"Leave Domain" crash on Centos 8

### ISSUE THREAD

**Issue by labalex** [PierreGode/Linux-Active-Directory-join-script#12]
Once added to AD and wanted to leave domain, the option "Leave Domain" crash, looping with that error:

![image](https://user-images.githubusercontent.com/7939167/69832565-1aaa7c00-11fd-11ea-8b3b-969296695580.png)

The only way to get out is to kill the process.

Thank you!

**Comment by PierreGode** [comment]
Will be fixed!

**Comment by PierreGode** [comment]
Hi! I have made changes but not able to test them today.

**Comment by PierreGode** [comment]
This has been solved. if you still have issues finding the domain make sure that you have your domain in searchdomain config and in /etc/hosts     host   host.domain.com
