### ISSUE TITLE
"Search with ldap" option in Centos 8

### ISSUE THREAD

**Issue by labalex** [PierreGode/Linux-Active-Directory-join-script#13]
Hi, the option "Search with ldap" create an error, it's trying to install a module with apt-get on CentOS 8:

![image](https://user-images.githubusercontent.com/7939167/69832621-665d2580-11fd-11ea-8c8d-977b922ef7df.png)

Thank you!

**Comment by PierreGode** [comment]
Ldap search has been poorly developed. I will put some effort in to it later. Thanks!
