### ISSUE TITLE
Random idea

### ISSUE THREAD

**Issue by labalex** [PierreGode/Linux-Active-Directory-join-script#14]
Hi Pierre, what about having an option to be able to use a answer file?

Thanks

**Comment by PierreGode** [comment]
Ok let me look at that! good Idea :)

**Comment by PierreGode** [comment]
I will add support for an (answer file) in early 2020 in progress 2020-02-13
I have start adding support for an answer file, It will take a couple of weeks.

**Comment by PierreGode** [comment]
Hi! I have done the change now. but is not 100% finished. support for CentoOS and Fedora is still needed. also not finished how to do with authentication.

**Comment by PierreGode** [comment]
Ubuntu now fully supports readfile. to generate encrypted password execute: sudo sh ADconnection.sh -p
you will have 3 files, a key pair and a locked file. you need all those files in the folder for autojoining.
Your ADadmin password is temporary decrypted into a variable during the "auth" moment. and the variable is cleared after. I suggest that you store at least the private key someware else. I added a comment in row 2232 about an example to curl the private key from some server.
