### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by barakvalzer** [PierreGode/Linux-Active-Directory-join-script#15]
Using Ubuntu LTS 18.04 and it work partially, everything beside login works, i can't su to the domain user even though id ADUSER@DOMAIN works.
tried it 3 times with waiting a while for it, are you sure that you dont need winbind + pam to allow logins?

**Comment by PierreGode** [comment]
Hi! 
In the generic setup "user@domain.com" is changed to only "user" removing @domain.com 
and home folder is set to /home/domain/user "override_homedir = /home/%d/%u"
So please try login with only "user"
pam configuration is made by the script.
after joining you can test is the user is responding with the command "id user" like you have done but also that should also list what groups the user is member of and one if the groups poping up needs to match the group that is added to the /etc/sudoers.d/sudoers that is autogenerated matching the hostname of the computer to grant you sudo access. also the computer object is autogenerated in active directory but not the AD group , make sure that you have created an AD group matching the group added in /etc/sudoers.d/sudoers and that your user is member of that  ADgroup.
the script is well used and worked today on ubuntu 18.04.

I use this script almost daily and is mostly configurated for my "setup" that I think is a good setup.
but if you requre for some reason to have another configuration please feel free to fork this repo and make the desired changes.

if you still have issues please mail me an output to pierre@gode.one

Best Regards Pierre
