### ISSUE TITLE
Add support for elementary OS

### ISSUE THREAD

**Issue by JBM1866** [PierreGode/Linux-Active-Directory-join-script#16]
Hello,
Great script!
Just wondering if you would be able to add support for elementary OS?
I have been able to use your script on the OS by adjusting the script to run as LinuxMint if it doesn't detect another OS...

Thanks,
JBM

**Comment by PierreGode** [comment]
Hi sure I can do that!

**Comment by PierreGode** [comment]
Support for Elemantary OS is completed. closing the ticket :)
