### ISSUE TITLE
can't login on q4os debian

### ISSUE THREAD

**Issue by xshion13** [PierreGode/Linux-Active-Directory-join-script#17]
i followed the instructions from the file and it said sucess and wait 3 minutes to be able to login, but nothin it says already joined to domain but when i pick "leave domain" it says realm not found

i am following the guide from [zentyal ](https://wiki.zentyal.org/wiki/Authenticating_Linux_client_against_Samba)to login correctly, i think something need to be modified to fix it

**Comment by PierreGode** [comment]
After is says success to Join. Can you test to run the command: id user      
It should show info about the AD user and list groups the user is member of.
User = short name in active directory, no need for user@domain.com.

**Comment by PierreGode** [comment]
Also in you can’t login try again to login in terminal mode to see if it can be an GUI bug.

**Comment by xshion13** [comment]
my ad server is working with zentyalaa.aa-mydomain.com 
loginuser is superadmin to register my computer
administrador is the main user on the computer
it says user does not exist when i try with any account except administrador where it says: 
uid=1000(administrador) gid=1001(administrador) grupos=1001(administrador),24(cd                                      rom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),100(users),109(netdev),114(bluetooth),119(lpadmin),1000(scanner)

if i try to change user in terminal it ask password for administrador but when i enter the password it says incorrect

**Comment by xshion13** [comment]
i tried to register again with the script it says: 
 * Resolving: _ldap._tcp.aa-mydomain.pe
 * Performing LDAP DSE lookup on: 167.2xx.2xx.52
 * Performing LDAP DSE lookup on: 192.168.0.2
 * Successfully discovered: aa-mydomain.pe
realm: Ya se ha unido a este dominio
AD join failed.please check your errors with journalctl -xe

**Comment by PierreGode** [comment]
Hi! I have made configurations. can you test again?
I don't have the possibility to test on CentOs this week
/Pierre

**Comment by xshion13** [comment]
Hello, i finished install with the script getting this:
sssd config.. OK
Realm not installed
Checking sudoers file..  OK
Checking sudoers groups.. OK
Checking PAM session configuration.. OK
Checking PAM auth configuration.. OK
InstallAD.sh: 275: InstallAD.sh: realm: not found
realm not found
Please reboot your machine and wait 3 min for Active Directory to sync before login
administrador@q4ospc9:~/Escritorio$
