### ISSUE TITLE
Ubuntu 18.04 error

### ISSUE THREAD

**Issue by labalex** [PierreGode/Linux-Active-Directory-join-script#20]
Hi, on new install of ubuntu 18.04 with latest upgraded package, I got those errors:
 * Unconditionally checking packages
 * Resolving required packages
 ! PackageKit not available: The name org.freedesktop.PackageKit was not provided by any .service files
 ! Necessary packages are not installed: sssd-tools sssd libnss-sss libpam-sss adcli
realm: Couldn't join realm: Necessary packages are not installed: sssd-tools sssd libnss-sss libpam-sss adcli

All the packages specified in the error are already installed.

Thanks

**Comment by PierreGode** [comment]
Hi I think I found the issue and solved it.
