### ISSUE TITLE
Script ADconnection.sh not working on Ubuntu 20.04 (readfile error)

### ISSUE THREAD

**Issue by anymor1024** [PierreGode/Linux-Active-Directory-join-script#21]
When I run script from command line:
sudo ADconnection.sh

an then I select choice 1. Add to domain
script ends with error:
Joining Ubuntu 20

grep: readfile: No such file or directory
grep: readfile: No such file or directory
error in readfile

**Comment by PierreGode** [comment]
Hi I found the bug and corrected it. I hope it works now.
/Pierre

**Comment by hakangit** [comment]
For Ubuntu 20.04 installation finishes like this:

`session required pam_mkhomedir.so skel=/etc/skel/ umask=0022
tee: /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf: No such file or directory
greeter-show-manual-login=true
tee: /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf: No such file or directory
allow-guest=false
realm: No default realm discovered
Realm not found
Checking sudoers file.. OK
Checking sudoers users.. OK
Checking PAM configuration.. OK
Checking PAM auth configuration..OK
sed: can't read /etc/sssd/sssd.conf: Permission denied
sed: can't read /etc/sssd/sssd.conf: Permission denied
sed: can't read /etc/sssd/sssd.conf: Permission denied
sed: couldn't open temporary file /etc/sedCnF5my: Permission denied
override_homedir = /home/%d/%u
override_homedir = /home/%d/%u
domain.tld
  type: kerberos
  realm-name: ****
  domain-name: ****
  configured: no
`

**Comment by TheSpaceXguy** [comment]
Hi! Seems it falls writing to sssd file. 
Unfortunately sssd is somehow protected so it forces the script to use sudo.

Please try with sudo sh ADconnection.sh

Best regards Pierre

Skickat från min iPhone

**Comment by hakangit** [comment]
Thanks my bad - All OK on stock 20.04 .
