### ISSUE TITLE
Little bug with ubuntu

### ISSUE THREAD

**Issue by MInus63** [PierreGode/Linux-Active-Directory-join-script#22]
Congratulations on this work

There’s a little bug when i'm open for first time my session into ubuntu (18.04LTS and 20.04LTS) with ad user account: 

the . bashrc and . profile files are not automatically created in my home

have you a solution for this concern?

Thank you

**Comment by PierreGode** [comment]
Oh Good one!  see that it is generated in U16. let me investigate.

**Comment by PierreGode** [comment]
Hi! I checked 90 computers joined with the script ( U16.04 and 18.04) they all had both bashrc and profile... 
can be later updates to script that is giving issues..  could you send me your join output to pierre@gode.one?
Best regards Pierre

**Comment by MInus63** [comment]
What files do you exactly need? where are located the join output?
