### ISSUE TITLE
local admin account is locked out

### ISSUE THREAD

**Issue by manit77** [PierreGode/Linux-Active-Directory-join-script#24]
I ran the script on Ubuntu 20.04 desktop and I can't login through ssh or the desktop. I can't login using AD or the local admin account. It is connected to AD but I can't authenticate. How can I gain access?

**Comment by manit77** [comment]
I was able to enable root access. but none of my local users can login to the desktop.

**Comment by PierreGode** [comment]
I believe that you have enabled ssh security. 
that should lock all accounts but local admin and AD user. Will need to take a look at it as it is not working as expected. I advice not use that I potion till I fixed it. 


In the file /etc/pam.d/common-auth
Look for the row=  auth required pam_listfile.so onerr=fail item=group sense=allow file=/etc/ssh/login.group.allowed

If you have that row just remove it.
That will give your users access.

**Comment by PierreGode** [comment]
I found the issue with SSH-security not supporting multiple local accounts (besides root + 1 account) 
I added support so the script will now add all local users to the ssh allow config.
but you have to purge the bad config yourself. 

In the file /etc/pam.d/common-auth
Look for the row= auth required pam_listfile.so onerr=fail item=group sense=allow file=/etc/ssh/login.group.allowed
and remove it. 
also remove the file /etc/ssh/login.group.allowed

if you want to use ssh security, then after purge of the bad config run the script again and select opting 5. after leaving domain.
exececute sudo git pull do download new version of the script. and then run it again to join again with working config.
/Pierre

**Comment by manit77** [comment]
Thanks for the fix. I'll test it out on my next Ubuntu build.
