### ISSUE TITLE
Please add Support for Zorin OS

### ISSUE THREAD

**Issue by ramon-kramer** [PierreGode/Linux-Active-Directory-join-script#25]
As Zorin OS is Ubuntu based (Zorin 15 is based on Ubuntu 18), it should be easy to implement :)
[https://zorinos.com/](https://zorinos.com/)

I was able to run the Script when i changed the following Strings:

Ubuntu > Zorin
ubuntu > zorin

if [ "$var" -eq "18" ] > [ "$var" -eq "15" ]

After that the device appeared in AD but i was not able to login with domain users.

**Comment by PierreGode** [comment]
Hi! I will Add Zorin OS. 

Coud you re-run the script on the joined computer and send me the output on option 2  pierre@gode.one

**Comment by PierreGode** [comment]
Hi Sorry Had not been able to fix earlier. could you give me the output of hostnamectl for zorin os?

**Comment by ramon-kramer** [comment]
Hi, here is the output:
```
   Static hostname: zorin-pc
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 8e5b386b740a45b6a436a5e3ff58738b
           Boot ID: 9018066f527b41d283970cca85082d11
    Virtualization: oracle
  Operating System: Zorin OS 15.3
            Kernel: Linux 5.4.0-65-generic
      Architecture: x86-64

```

**Comment by PierreGode** [comment]
Suppot added please test :)

**Comment by ramon-kramer** [comment]
hi, will test soon, was quite busy. ZorinOS 16 now offers this feature for new installations, but is still useful for migration into domain after installation.
