### ISSUE TITLE
Don't find user in my active directory domain

### ISSUE THREAD

**Issue by MInus63** [PierreGode/Linux-Active-Directory-join-script#26]
Hi

I'm using your script on ubuntu 20.04.2LTS

First of all, when i start ADconnection.sh, i have an error with adcli (may be the error come from line 824-826)

The error is: can't find adcli version 0.8.2-1

After that, the script finish after asking me my admin domain login and password:

```
Realm=domain.lan
Joining Ubuntu 20

Please type Admin user:
admserrec
grep: readfile: Aucun fichier ou dossier de ce type
 * Resolving: _ldap._tcp.domain.lan
 * Performing LDAP DSE lookup on: 172.16.0.2
 * Performing LDAP DSE lookup on: 172.16.0.1
 * Successfully discovered: phimeca.lan
Password for domainadmin:
 * Assuming packages are installed
 * LANG=C /usr/sbin/adcli join --verbose --domain domain.lan --domain-realm domain.LAN --domain-controller 172.16.0.2 --login-type user --login-user admindomain --stdin-password
 * Using domain name: domain.lan
 * Calculated computer account name from fqdn: BMW
 * Using domain realm: domain.lan
 * Sending NetLogon ping to domain controller: 172.16.0.2
 * Received NetLogon info from: server1.domain.lan
 * Wrote out krb5.conf snippet to /var/cache/realmd/adcli-krb5-kgGTD9/krb5.d/adcli-krb5-conf-6NToY5
 * Authenticated as user: admindomain@DOMAIN.LAN
 * Using GSS-SPNEGO for SASL bind
 * Looked up short domain name: domain
 * Looked up domain SID: S-1-5-21-545202174-1067577326-598125351
 * Using fully qualified name: bmw
 * Using domain name: domain.lan
 * Using computer account name: BMW
 * Using domain realm: domain.lan
 * Calculated computer account name from fqdn: BMW
 * Generated 120 character computer password
 * Using keytab: FILE:/etc/krb5.keytab
 * Found computer account for BMW$ at: CN=BMW,CN=Computers,DC=domain,DC=lan
 * Sending NetLogon ping to domain controller: 172.16.0.2
 * Received NetLogon info from: server1.domain.lan
 * Set computer password
 * Retrieved kvno '57' for computer account in directory: CN=BMW,CN=Computers,DC=domain,DC=lan
 * Checking host/BMW
 *    Added host/BMW
 * Checking RestrictedKrbHost/BMW
 *    Added RestrictedKrbHost/BMW
 * Checking HOST/bmw.domain.lan
 *    Added HOST/bmw.domain.lan
 * Discovered which keytab salt to use
 * Added the entries to the keytab: BMW$@domain.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: host/BMW@domain.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: RestrictedKrbHost/BMW@domain.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: HOST/bmw.domain.lan@domain.LAN: FILE:/etc/krb5.keytab
 * /usr/sbin/update-rc.d sssd enable
 * Successfully enrolled machine in realm

```
But, after a reboot or not, i can't find any user with the command id user, and i can't open any session (access denied) 

I try the error option of your script and this is the answer:

```
Realm configured?.. YES
Checking sudoers file.. FAIL
Checking PAM configuration.. FAIL
Checking PAM auth configuration.. SSH security not configured
```

the only one modify i made of your script is with this command:
`sed -i -e 's/override_homedir = \/home\/%d\/%u/override_homedir = \/home\/%u/g' Linux-Active-Directory-join-script/ADconnection.sh`

Thank you for your help, i don’t know what’s going on

**Comment by PierreGode** [comment]
So this was a big issue on 20.04 the new version of adcli did not work, there is some bug in it. the only way to make the join work properly was to revert to an older version of adcli. 

please try to manually install an older version (0.8) of adcli https://www.ubuntuupdates.org/package/core/bionic/universe/updates/adcli

and then rejoin.

let me know if it works so I can adjust the script.

**Comment by PierreGode** [comment]
line 824 wants to run sudo apt install adcli=0.8.2-1 -y --allow-downgrades 
could be that the have removed that version from 20.04. I can still find it on my 18.04

**Comment by MInus63** [comment]
Thank you
So i tried your solution:
Install adcli 0.8.2.1 with

```
wget http://archive.ubuntu.com/ubuntu/pool/universe/a/adcli/adcli_0.8.2-1_amd64.deb
dpkg -i adcli_0.8.2-1_amd64.deb
apt-get install -f
```
first try to hold the package with 

apt-mark hold adcli

For avoid upgrade to 0.9

Start your sh integration program; it crash

after that i unhold the package

Start your integration program, everything seems to be allright, but...the package adcli upgrade to 0.9 and my OS is not in the active directory domain (no answer to "id user" for exemple).

You have a solution?

**Comment by MInus63** [comment]
Up?

**Comment by PierreGode** [comment]
Hi! yes. What I do is:  sudo apt install adcli=0.8.2-1 -y --allow-downgrades

**Comment by PierreGode** [comment]
I changed #sudo apt-get --only-upgrade install adcli
sudo apt install adcli=0.8.2-1 -y --allow-downgrades in rows 1000 1008
I need to test this and review

**Comment by MInus63** [comment]
i change sudo apt-get --only-upgrade install adcli
to
sudo apt install adcli=0.8.2-1 -y --allow-downgrades

in line 824, 1000 and 1008

Everything seems to be OK but
Same problem, when i ask "id user" (id Minus63 which is ad user member) the system answer "user don't exist" (Minus63 don't exist)  and of course i can't open my session.

**Comment by PierreGode** [comment]
what is you output of realm discover ?
you can mail me at pierre@gode.one 
Sad To hear.. I will be in office tomorrow and will be able to test this.

**Comment by MInus63** [comment]
I just sent you the email with the information
