### ISSUE TITLE
Please Add SSH Key auth via LDAP

### ISSUE THREAD

**Issue by stealthbootc** [PierreGode/Linux-Active-Directory-join-script#27]
Hello could you add support for the below in sssd so that we can use AD to ssh key auth. We do this now but its not nearly as clean as your script. Its hacked together :)

ldap_user_extra_attrs = altSecurityIdentities:altSecurityIdentities
ldap_user_ssh_public_key = altSecurityIdentities

**Comment by PierreGode** [comment]
I have added 
############################## altSecurityIdentities ###############################################
#sudo echo "
#ldap_user_extra_attrs = altSecurityIdentities:altSecurityIdentities
#ldap_user_ssh_public_key = altSecurityIdentities" | sudo tee -a /etc/sssd/sssd.conf

at row 324 -327 ( row will change after future updates just search the file for altSecurityIdentities)

the will add those rows to your domain section in sssd.conf 

just remove the # from the rows before runnung the script.

let me know if you get any issues.

/Pierre
