### ISSUE TITLE
"realm not found"

### ISSUE THREAD

**Issue by teddue** [PierreGode/Linux-Active-Directory-join-script#28]
After executing the script on Ubuntu 20.4.2 I cannot sign on with domain accounts (they're correctly resolved though).
When I use the Check for errors function of the script I get the message "realm not found"

**Comment by PierreGode** [comment]
Hi! sorry for late response, you can test checking your sssd information with realm discover yourdomain.com
some times something fails. I have not found the issue jet. but i helps to run the script again with option leave domain and the again to join.
