### ISSUE TITLE
OU specification

### ISSUE THREAD

**Issue by wi5nia** [PierreGode/Linux-Active-Directory-join-script#32]
It would be nice if the script would allow to specify which OU to join

**Comment by PierreGode** [comment]
Hi! good one. thank you
I have done a test implementation in dev branch for ubuntu.
what distro are you using?

in DEV you can now specify OU in the readfile. 
I will be able to test this next week. but if you use Ubuntu feel free to test checking out the dev branch and adding the ou to the readfile before joining.
/Pierre

**Comment by wi5nia** [comment]
Yes, doing Ubuntu so I will test it later :)

**Comment by PierreGode** [comment]
I was able to test it now. I have merged the commit to master now.
