### ISSUE TITLE
CentOS

### ISSUE THREAD

**Issue by TheSpaceXguy** [PierreGode/Linux-Active-Directory-join-script#5]
Hi! 
Josh here.
Just want to say thanks for an amazing script, saved me a lot of work!
About 
Row 663 # Functional but ugly
Are you going to update this?, I mean.. It works perfect but it is ugly.

Best Regards Josh

**Comment by PierreGode** [comment]
Hi! yes, this is not an priority but it will be fixed :)
Best regards Pierre

**Comment by PierreGode** [comment]
This issue has been resolved
