### ISSUE TITLE
Possible to force the ad server name?

### ISSUE THREAD

**Issue by robmorin** [PierreGode/Linux-Active-Directory-join-script#6]
Hello, I am testing an AD server on a network that already uses FreeIPA(openldap). I am trying to migrate to MSAD. SO i have a test windows server 2012 server up and a test Centos 7 server(VM)

So when i run the script it detects my FreeIPA server and the domain, but i dont want to use the server it finds, I want to force it to use my test MSAD server. How can i do this?

Thanks...

**Comment by PierreGode** [comment]
Hi!
Thank you for using my script.
when the script detects the domain it should ask you if you want to use it or not, there you can select "no" and a line will be presented, there you can manually type the server you wish to test.
Best Regards 
Pierre

**Comment by robmorin** [comment]
Thanks for the quick reply!

Here is an output from a test server it finds my current 
FreeIPA(192.168.2.251) server, but i do not want to use that, i want to 
use another server(192.168.2.37).
I commented out the clear command from the script so i can troubleshoot 
better... maybe you should add an option for that?
I assume it find the srv record via DNS?
I am using Centos 7, the latest version and MSAD Server 2012

Thanks...

[root@test-centos7 ~]# ADconnection.sh
   Active directory connection tool
       Created by Pierre Goude
  This script will edit several critical files..
   DO NOT attempt this without expert knowledge

1) Join to AD on Linux (Ubuntu/Rasbian/Kali/Fedora)
2) Check for errors
3) Search with ldap
4) Reauthenticate
5) Update from Likewise to Realmd for Ubuntu 14
6) Leave Domain

Please enter a menu option and enter or enter to exit.
1
Installing on Linux Client/Server
Cent OS detected
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
  * base: centos.mirror.ca.planethoster.net
  * extras: mirror.calgah.com
  * updates: mirror.calgah.com
Package realmd-0.16.1-9.el7.x86_64 already installed and latest version
Package sssd-1.16.0-19.el7_5.5.x86_64 already installed and latest version
Package oddjob-0.31.5-4.el7.x86_64 already installed and latest version
Package oddjob-mkhomedir-0.31.5-4.el7.x86_64 already installed and 
latest version
Package adcli-0.8.1-4.el7.x86_64 already installed and latest version
Package samba-common-tools-4.7.1-9.el7_5.x86_64 already installed and 
latest version
Package samba-common-4.7.1-9.el7_5.noarch already installed and latest 
version
Nothing to do
realm: No default realm discovered
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
             [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] 
[-Q tos]
             [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
             [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
              [-l preload] [-m mark] [-M pmtudisc_option]
              [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
              [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
              [-W timeout] destination
I searched for an available domain and found nothing, please type your 
domain manually below...
Please enter the domain you wish to join:
hardent.com
I Please enter AD admin user
administrator
Please enter AD admin user:
administrator
Realm= hardent.com

  * Resolving: _ldap._tcp.hardent.com
  * Performing LDAP DSE lookup on: 192.168.2.251
  * Successfully discovered: hardent.com
Password for administrator:

**** I di da ctl-c here to stop the script ****

  * Assuming packages are installed
  * LANG=C /usr/sbin/ipa-client-install --domain hardent.com --realm 
HARDENT.COM --mkhomedir --enable-dns-updates --unattended --force-join 
--principal administrator -W --force-ntpd
  ! Failed to enroll machine in realm: Failed to execute child process 
"/usr/sbin/ipa-client-install" (No such file or directory)
realm: Couldn't join realm: Failed to enroll machine in realm. See 
diagnostics.
AD join failed.please check that computer object is already created and 
test again

Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca

**Comment by robmorin** [comment]
FYI, i had to also manually install ipa client
yum install ipa-client

As the script did not install it , not sure if thats intentional or not?

The server was joined to my freeipa realm just fine and user can auth 
just fine....

But i need to test against my MSAD instead...


Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca

**Comment by PierreGode** [comment]
I see that you manually enter hardent.com and it points to 192.168.2.251 and not 192.168.2.37
I suggest that you verify the server with:  
realm discover--all             | Show all discovered realms (in various configurations).
-- | --
--client-software=xxx        | Only discover realms for which we can use the given client software. Possible       values include sssd or winbind.
--server-software=xxx       | Only discover realms which run the given server software. Possible values include active-directory or ipa.

also try realm discover domain and realm list


I use MSAD and it works fine.
I overlooked spa-client, I have added it now, thanks.
yes it looks for a dns record, never tried with an ip..
and the try to join with a one liner, sudo realm join -v -U $ADMIN $DOMAIN --install=/
Just to rule out script issues.

/Pierre Gode

**Comment by PierreGode** [comment]
I saw the issue with username be promoted 2 times, I have solved it now, 
please do a git pull.
/Pierre

**Comment by robmorin** [comment]
Ok your username thing was fixed... so here is the output of the join.....

[root@test-centos7 Linux-Active-Directory-join-script]# ./ADconnection.sh


   Active directory connection tool
       Created by Pierre Goude
  This script will edit several critical files..
   DO NOT attempt this without expert knowledge

1) Join to AD on Linux (Ubuntu/Rasbian/Kali/Fedora)
2) Check for errors
3) Search with ldap
4) Reauthenticate
5) Update from Likewise to Realmd for Ubuntu 14
6) Leave Domain

Please enter a menu option and enter or enter to exit.
1

Installing on Linux Client/Server
Cent OS detected
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
  * base: centos.mirror.ca.planethoster.net
  * extras: mirror.calgah.com
  * updates: mirror.calgah.com
Package realmd-0.16.1-9.el7.x86_64 already installed and latest version
Package sssd-1.16.0-19.el7_5.5.x86_64 already installed and latest version
Package oddjob-0.31.5-4.el7.x86_64 already installed and latest version
Package oddjob-mkhomedir-0.31.5-4.el7.x86_64 already installed and 
latest version
Package adcli-0.8.1-4.el7.x86_64 already installed and latest version
Package samba-common-tools-4.7.1-9.el7_5.x86_64 already installed and 
latest version
Package samba-common-4.7.1-9.el7_5.noarch already installed and latest 
version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
  * base: centos.mirror.ca.planethoster.net
  * extras: mirror.calgah.com
  * updates: mirror.calgah.com
Package ipa-client-4.5.4-10.el7.centos.3.x86_64 already installed and 
latest version
Nothing to do
realm: No default realm discovered
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
             [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] 
[-Q tos]
             [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
             [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
              [-l preload] [-m mark] [-M pmtudisc_option]
              [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
              [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
              [-W timeout] destination

I searched for an available domain and found nothing, please type your 
domain manually below...
Please enter the domain you wish to join:
hardent.com
I Please enter AD admin user
rmorin
Realm= hardent.com

  * Resolving: _ldap._tcp.hardent.com
  * Performing LDAP DSE lookup on: 192.168.2.37
  * Successfully discovered: hardent.com
Password for rmorin:
  * Assuming packages are installed
  * LANG=C /usr/bin/net -s /var/cache/realmd/realmd-smb-conf.8UJ0OZ -U 
rmorin ads join hardent.com
Enter rmorin's password:
Failed to join domain: failed to lookup DC info for domain 'hardent.com' 
over rpc: The attempted logon is invalid. This is either due to a bad 
username or authentication information.
  ! Joining the domain hardent.com failed
realm: Couldn't join realm: Joining the domain hardent.com failed
AD join failed.please check that computer object is already created and 
test again



Here is a test using ldapsearch to show that i can connect successfully 
to that AD

[root@test-centos7 Linux-Active-Directory-join-script]# ldapsearch -h 
ad-1.hardent.com -b "dc=hardent,dc=com" -D "CN=Rob 
Morin,CN=Users,dc=hardent,dc=com" -s sub "objectclass=person" -x -w 
password1234|grep Rob

# Rob Morin, Users, hardent.com
dn: CN=Rob Morin,CN=Users,DC=hardent,DC=com
cn: Rob Morin
givenName: Rob
distinguishedName: CN=Rob Morin,CN=Users,DC=hardent,DC=com
displayName: Rob Morin
name: Rob Morin

Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca

**Comment by robmorin** [comment]
trying to join manually

[root@test-centos7 Linux-Active-Directory-join-script]# realm join -v -U 
rmorin HARDENT.COM --install=/
  * Resolving: _ldap._tcp.hardent.com
  * Performing LDAP DSE lookup on: 192.168.2.37
  * Successfully discovered: hardent.com
Password for rmorin:
  * Assuming packages are installed
  * LANG=C /usr/bin/net -s /var/cache/realmd/realmd-smb-conf.J3OCPZ -U 
rmorin ads join hardent.com
Enter rmorin's password:
Failed to join domain: failed to lookup DC info for domain 'hardent.com' 
over rpc: The attempted logon is invalid. This is either due to a bad 
username or authentication information.
  ! Joining the domain hardent.com failed
realm: Couldn't join realm: Joining the domain hardent.com failed

Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca

**Comment by robmorin** [comment]
Ok it works now!

I fixed up dns so it can properly find ldap server... I changed all the 
lines that had auth-1 to ad-1 and restart dns and all work just fine...

Maybe you should make a note that part of requirement is to have DNS 
functioning properly ??
I will continue with a fresh server install and let you know how it goes...

Thanks for all your help so far!

srv-host = _ldap._tcp.dc._msdcs.HARDENT.COM,ad-1.hardent.com,389
srv-host =_kerberos-master._tcp.hardent.com,ad-1.hardent.com,88
srv-host =_kerberos-master._tcp.hardent.com,auth-2.hardent.com,88
srv-host =_kerberos-master._udp.hardent.com,ad-1.hardent.com,88
srv-host =_kerberos-master._udp.hardent.com,auth-2.hardent.com,88
srv-host 
=_kerberos._tcp.Default-First-Site-Name._sites.dc._msdcs,ad-1.hardent.com,88
srv-host =_kerberos._tcp.dc._msdcs,ad-1.hardent.com,88
srv-host =_kerberos._tcp.hardent.com,ad-1.hardent.com,88
srv-host =_kerberos._tcp.hardent.com,auth-2.hardent.com,88
srv-host 
=_kerberos._udp.Default-First-Site-Name._sites.dc._msdcs,ad-1.hardent.com,88
srv-host =_kerberos._udp.dc._msdcs,ad-1.hardent.com,88
srv-host =_kerberos._udp.hardent.com,ad-1.hardent.com,88
srv-host =_kerberos._udp.hardent.com,auth-2.hardent.com,88
srv-host =_kpasswd._tcp.hardent.com,ad-1.hardent.com,88
srv-host =_kpasswd._tcp.hardent.com,auth-2.hardent.com,88
srv-host =_kpasswd._udp.hardent.com,ad-1.hardent.com,88
srv-host =_kpasswd._udp.hardent.com,auth-2.hardent.com,88
srv-host 
=_ldap._tcp.Default-First-Site-Name._sites.dc._msdcs,ad-1.hardent.com,389
srv-host =_ldap._tcp.dc._msdcs,ad-1.hardent.com,389
srv-host =_ldap._tcp.hardent.com,ad-1.hardent.com,389
srv-host =_ldap._tcp.hardent.com,ad-2.hardent.com,389
srv-host =_ntp._udp.hardent.com,ntp.hardent.com,123


Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca

**Comment by PierreGode** [comment]
well then we know that is not the script failing.
is the RPCSS service running?

execute: journalctl -xe  after join attempt,  you can get more information then.

There is no problems in creating two domains on the same subnet as long the domain name differs. 
But you cannot use DHCP on this network. Because domain members may get different DNS settings which can create name resolution issues.
is the domain name same for "both servers" ?
has the both servers DHCP and DNS?
Is the DNS working properly?

/Pierre

**Comment by robmorin** [comment]
But a question, the users home dir is setup as 
/home/domain.com/username... if i migrate to ad i need the home dir to 
be /home/username. How would i modify the script to accommodate that?

The reason being is that we have many serves that mount /home from a nas 
in /home, so it needs to stay the same...
Thanks..

Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca

**Comment by PierreGode** [comment]
Oh! Nice!

**Comment by PierreGode** [comment]
you can modify it by editing the file /etc/sssd/sssd.conf 
standard is override_homedir = /home/%d/%u     it should work with     override_homedir = /home/%u

**Comment by robmorin** [comment]
Ok cool i will try that....

on another note when i try to leave a domain the below happens...  I 
have to press 6 twice initial time and after weird display...


[rmorin@test-centos7 Linux-Active-Directory-join-script]$ ADconnection.sh
   Active directory connection tool
       Created by Pierre Goude
  This script will edit several critical files..
   DO NOT attempt this without expert knowledge

1) Join to AD on Linux (Ubuntu/Rasbian/Kali/Fedora)
2) Check for errors
3) Search with ldap
4) Reauthenticate
5) Update from Likewise to Realmd for Ubuntu 14
6) Leave Domain

Please enter a menu option and enter or enter to exit.
6
/usr/local/bin/ADconnection.sh: line 1544: opt: command not found
\033[32m   Active directory connection tool             \033[32m
\033[32m       Created by Pierre Goude                  \033[32m
\033[32m This script will edit several critical files.. \033[32m
\033[32m  DO NOT attempt this without expert knowledge  \033[32m
\033[m                                                    \033[m
\033[36m*\033[33m 1)\033[36m Join to AD on Linux 
(Ubuntu/Rasbian/Kali/Fedora/Debian)    \033[m
\033[36m*\033[33m 2)\033[36m Check for errors    \033[m
\033[36m*\033[33m 3)\033[36m Search with ldap              \033[m
\033[36m*\033[33m 4)\033[36m Reauthenticate   \033[m
\033[36m*\033[33m 5)\033[36m Update from Likewise to Realmd for Ubuntu 
14 \033[m
\033[36m*\033[33m 6)\033[36m Leave Domain             \033[m
\033[m                                                    \033[m
Please enter a menu option and enter or \033[31menter to exit. \033[m

Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca

**Comment by PierreGode** [comment]
Leave should be solved now.

**Comment by robmorin** [comment]
I sent an email to you at your webbhatt email for troubling shooting... 
or should i still send bugs to this address?

Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca

**Comment by PierreGode** [comment]
I have now verified that the script works in CentOS, I also made small improvments to the CentOS section.
I am closing this ticket and we can continue on the mail conversation.
If you get any other script related issues, please open a new ticket.
/pierre
