### ISSUE TITLE
Access granted even if not in designeted groups

### ISSUE THREAD

**Issue by labalex** [PierreGode/Linux-Active-Directory-join-script#8]
Hi, on centos 7 if you say yes to use login.group.allowed and give not the users sudo right, they will be able to ssh to the machine, with the -sh-4.2$ environment

That said, they will be able to try to brute force the server without any security mesure.

Users not in the login.group.allowed group should no be able to connect.

Thanks

Alex

**Comment by PierreGode** [comment]
And that is how it should work! I will test this and pach.
I will update you on the issue!

**Comment by PierreGode** [comment]
Hi! I found the issue and corrected it!
I have tested and all users not member of AD-group are blocked.
Please verify.

Best regars Pierre

**Comment by PierreGode** [comment]
Hi I solved the issue and closing it now. please let me know if you have issues.
